cask_args appdir: "/Applications"
tap "homebrew/cask"
# Vim
brew 'vim', args: ['with-override-system-vi']
brew 'neovim', args: ['HEAD']
brew 'fzf'

# Package managers
brew 'rbenv'
brew 'pipenv'
brew 'nvm'

# Languages
brew 'go'

# Database-related
brew 'postgresql'
brew 'redis'
brew 'mongodb'

# Utility
brew 'tmux'
brew 'ripgrep'
brew 'fd'
brew 'bash'
brew 'git'
brew 'bash-completion'
brew 'stow'
brew 'xclip'
brew 'tree'
brew 'trash'

tap 'heroku/brew'
brew 'heroku'

## Casks ##
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'google-backup-and-sync'
cask 'iina'
cask 'iterm2'
cask 'keepassxc'
cask 'postman'
cask 'postico'
cask 'visual-studio-code'
cask 'xquartz' # Needed for xclip
